# Generated by Django 5.1.3 on 2024-12-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_role_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_farmer_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
