# Generated by Django 5.1.3 on 2024-12-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0007_customuser_is_approved_customuser_is_buyer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='full_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='short_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
