# Generated by Django 5.1.3 on 2024-12-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0010_remove_customuser_photo_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.URLField()),
                ('short_message', models.TextField()),
                ('full_message', models.TextField()),
            ],
        ),
    ]
