# Generated by Django 5.1.3 on 2024-12-04 07:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('farmers', '0005_farmer_remove_product_owner_remove_product_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='roduct_type',
            new_name='product_type',
        ),
    ]
