# Generated by Django 5.1.3 on 2024-12-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('farmers', '0009_product_uploaded_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=100)),
                ('short_message', models.CharField(max_length=200)),
                ('full_message', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='messages/')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
