# Generated by Django 5.1.3 on 2024-12-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('farmers', '0011_product_is_approved_product_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')],
                                   default='pending', max_length=10),
        ),
    ]
