# Generated by Django 5.1.3 on 2024-12-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('farmers', '0013_remove_product_is_submitted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
